/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "Helpers/logger.h"
#include "usbd_framework.h" //application layer should deal only with the framework layer and not directly with driver layer
//Appln layer calls APIs in framework layer which inturn call APIs in driver layer

int main(void)
{
	log_info("Program entrypoint.");

	usbd_init();

	for(;;);
}
